services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:7-alpine
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    # Forza l'ascolto su tutte le interfacce
    command: ["redis-server", "--protected-mode", "no"]
    expose:
      - "6379"
    networks:
      default:
        aliases:
          - redis